Repository august-thirty-first/backend, pull requests merged in 2023-08, with the labels that each got.

#22 [bug] : response 메시지 send 해주어 pending 해결
  nestjs/src/auth/auth.controller.ts
Labels: 🐛bug

#33 Refactor] 31 global-pipe-validation 설정하기
  nestjs/package-lock.json
  nestjs/package.json
  nestjs/src/main.ts
Labels: ♻️refactor

#32 Refactor] 임시 jwt 토큰 일반 jwt 토큰 분리
  nestjs/src/app.module.ts
  nestjs/src/auth/auth.module.ts
  nestjs/src/auth/auth.service.spec.ts
  nestjs/src/auth/auth.service.ts
  nestjs/src/jwt/interface/jwt.type.ts
  nestjs/src/jwt/jwt.module.ts
  nestjs/src/jwt/temp-jwt.module.ts
  nestjs/src/passports/passports.module.ts
Labels: ♻️refactor

#56 래더 게임을 위한 대기큐 만들기
  nestjs/src/socket/game/game.gateway.ts
Labels: 💫feat

#57 Feat 채팅 기능 구현
  docker/nestjs/Dockerfile
  nestjs/nest-cli.json
  nestjs/package-lock.json
  nestjs/package.json
  nestjs/src/app.module.ts
  nestjs/src/chat/chat.controller.spec.ts
  nestjs/src/chat/chat.controller.ts
  nestjs/src/chat/chat.module.ts
  nestjs/src/chat/chat.respository.ts
  nestjs/src/chat/chat.service.spec.ts
  nestjs/src/chat/chat.service.ts
  nestjs/src/chat/chatParticipant.repository.ts
  nestjs/src/chat/dto/chat.dto.ts
  nestjs/src/chat/dto/chatCreate.dto.ts
  nestjs/src/chat/dto/chatParticipant.dto.ts
  nestjs/src/chat/dto/chatParticipantCreate.dto.ts
  nestjs/src/chat/entities/chat.entity.ts
  nestjs/src/chat/entities/chatParticipant.entity.ts
  nestjs/src/chat/enum/chat.status.enum.ts
  nestjs/src/chat/enum/chatParticipant.status.enum.ts
  nestjs/src/main.ts
  nestjs/src/socket/home/home.gateway.ts
  nestjs/src/socket/home/home.module.ts
Labels: 💫feat

#63 Feat 채팅방 생성 및 참가 로직 변경
  nestjs/src/chat/chat.controller.ts
  nestjs/src/chat/chat.service.ts
  nestjs/src/chat/chatParticipant.repository.ts
  nestjs/src/chat/dto/chatParticipant.dto.ts
  nestjs/src/chat/dto/chatParticipantCreate.dto.ts
  nestjs/src/chat/entities/chatParticipant.entity.ts
  nestjs/src/chat/enum/chatParticipant.authority.enum.ts
  nestjs/src/socket/home/home.gateway.ts
Labels: 💫feat

#66 Feat chat테이블 delete query fail 오류
  nestjs/src/chat/chat.service.ts
  nestjs/src/chat/entities/chat.entity.ts
  nestjs/src/chat/entities/chatParticipant.entity.ts
Labels: 🐛bug

#70 [Fix]: Chat의 Status에 따른 password의 옳바른 처리
  nestjs/src/chat/chat.service.ts
Labels: 🐛bug

#71 게임 매칭 완료시 게임 객체 생성 후 관리 로직 추가
  nestjs/src/socket/game/class/game.ts
  nestjs/src/socket/game/class/gamePlayer.ts
  nestjs/src/socket/game/class/renderInfo.ts
  nestjs/src/socket/game/class/user.ts
  nestjs/src/socket/game/dto/ready.dto.ts
  nestjs/src/socket/game/gameSocket.gateway.ts
  nestjs/src/socket/game/gameSocket.module.ts
  nestjs/src/socket/game/gameSocket.service.ts
  nestjs/src/socket/game/utils/getMostFrequencyItem.ts
  nestjs/src/socket/game/utils/setCountMap.ts
Labels: 🐛bug, 💫feat

#72 게임 서버에 필요한 객체 생성
  nestjs/src/app.module.ts
  nestjs/src/game/dto/gameOption.dto.ts
  nestjs/src/game/enum/gameOption.enum.ts
  nestjs/src/game/game.controller.spec.ts
  nestjs/src/game/game.controller.ts
  nestjs/src/game/game.module.ts
  nestjs/src/game/game.service.spec.ts
  nestjs/src/game/game.service.ts
  nestjs/src/socket/game/class/ball.ts
  nestjs/src/socket/game/class/bar.ts
  nestjs/src/socket/game/class/game.ts
  nestjs/src/socket/game/class/gameHistory.ts
  nestjs/src/socket/game/class/gameMap.ts
  nestjs/src/socket/game/class/gamePlayer.ts
  nestjs/src/socket/game/class/positon.ts
  nestjs/src/socket/game/class/renderInfo.ts
  nestjs/src/socket/game/class/user.ts
  nestjs/src/socket/game/dto/ready.dto.ts
  nestjs/src/socket/game/enum/gameStatus.enum.ts
  nestjs/src/socket/game/enum/initStatus.enum.ts
  nestjs/src/socket/game/enum/playerSide.enum.ts
  nestjs/src/socket/game/enum/userStatus.enum.ts
  nestjs/src/socket/game/game.gateway.ts
  nestjs/src/socket/game/game.module.ts
  nestjs/src/socket/game/gameSocket.gateway.spec.ts
  nestjs/src/socket/game/gameSocket.gateway.ts
  nestjs/src/socket/game/gameSocket.module.ts
  nestjs/src/socket/game/gameSocket.service.ts
  nestjs/src/socket/game/utils/getMostFrequencyItem.ts
  nestjs/src/socket/game/utils/setCountMap.ts
Labels: 💫feat, ⚙️chore

#78 Feat 55 친구 기능 만들기
  nestjs/src/app.module.ts
  nestjs/src/friend/dto/friendCommon.dto.ts
  nestjs/src/friend/dto/friendCommonRequestBody.dto.ts
  nestjs/src/friend/dto/friendGetResponse.dto.ts
  nestjs/src/friend/dto/friendRequesting.dto.ts
  nestjs/src/friend/entities/FriendRequesting.entity.ts
  nestjs/src/friend/entities/Friends.entity.ts
  nestjs/src/friend/friend.controller.ts
  nestjs/src/friend/friend.module.ts
  nestjs/src/friend/friend.service.ts
  nestjs/src/friend/friendRequesting.repository.ts
  nestjs/src/friend/friends.repository.ts
  nestjs/src/profile/dto/searchUser.dto.ts
  nestjs/src/profile/profile.controller.ts
  nestjs/src/profile/profile.module.ts
  nestjs/src/profile/profile.service.ts
Labels: 💫feat

#98 keydown 이벤트 처리 로직 구현
  nestjs/src/socket/game/enum/initStatus.enum.ts
  nestjs/src/socket/game/gameSocket.gateway.ts
Labels: 🐛bug, 💫feat

#97 ball 객체와 bar 객체의 모양을 표현할 수 있는 프로퍼티 추가
  nestjs/src/socket/game/class/ball.ts
  nestjs/src/socket/game/class/bar.ts
  nestjs/src/socket/game/class/gamePlayer.ts
  nestjs/src/socket/game/class/renderInfo.ts
  nestjs/src/socket/game/enum/initStatus.enum.ts
  nestjs/src/socket/game/gameSocket.gateway.ts
  nestjs/src/socket/game/gameSocket.service.ts
Labels: 💫feat, ⚙️chore

#100 ball 움직임 및 충돌 구현
  nestjs/src/socket/game/class/bar.ts
  nestjs/src/socket/game/gameSocket.gateway.ts
  nestjs/src/socket/game/gameSocket.service.ts
Labels: 💫feat

#104 Feat chatservicets파일 리팩터링
  nestjs/src/chat/chat.controller.ts
  nestjs/src/chat/chat.respository.ts
  nestjs/src/chat/chat.service.ts
  nestjs/src/chat/chatParticipant.repository.ts
  nestjs/src/socket/home/dto/message.dto.ts
  nestjs/src/socket/home/dto/roomId.dto.ts
  nestjs/src/socket/home/home.gateway.ts
Labels: 🐛bug, ♻️refactor

#106 공 속도가 너무 느리게 초기화 되는 문제 해결
  nestjs/src/socket/game/class/ball.ts
  nestjs/src/socket/game/enum/initStatus.enum.ts
  nestjs/src/socket/game/utils/getRandomNumberRange.ts
Labels: 🐛bug

#109 Dev game 브랜치 release 1.0으로 병합 (중간 점검)
  nestjs/src/app.module.ts
  nestjs/src/game/dto/gameOption.dto.ts
  nestjs/src/game/enum/gameOption.enum.ts
  nestjs/src/game/game.controller.spec.ts
  nestjs/src/game/game.controller.ts
  nestjs/src/game/game.module.ts
  nestjs/src/game/game.service.spec.ts
  nestjs/src/game/game.service.ts
  nestjs/src/socket/game/class/ball.ts
  nestjs/src/socket/game/class/bar.ts
  nestjs/src/socket/game/class/game.ts
  nestjs/src/socket/game/class/gameHistory.ts
  nestjs/src/socket/game/class/gameMap.ts
  nestjs/src/socket/game/class/gamePlayer.ts
  nestjs/src/socket/game/class/positon.ts
  nestjs/src/socket/game/class/renderInfo.ts
  nestjs/src/socket/game/class/user.ts
  nestjs/src/socket/game/class/velocity.ts
  nestjs/src/socket/game/dto/frameSize.dto.ts
  nestjs/src/socket/game/dto/ready.dto.ts
  nestjs/src/socket/game/enum/gameStatus.enum.ts
  nestjs/src/socket/game/enum/initStatus.enum.ts
  nestjs/src/socket/game/enum/playerSide.enum.ts
  nestjs/src/socket/game/enum/userStatus.enum.ts
  nestjs/src/socket/game/game.gateway.ts
  nestjs/src/socket/game/game.module.ts
  nestjs/src/socket/game/gameSocket.gateway.spec.ts
  nestjs/src/socket/game/gameSocket.gateway.ts
  nestjs/src/socket/game/gameSocket.module.ts
  nestjs/src/socket/game/gameSocket.service.ts
  nestjs/src/socket/game/utils/getMostFrequencyItem.ts
  nestjs/src/socket/game/utils/getRandomNumberRange.ts
  nestjs/src/socket/game/utils/setCountMap.ts
Labels: ⚙️chore

#118 [Feat]: BOSS가 방을 나갔을때 처리
  nestjs/src/chat/chat.controller.ts
  nestjs/src/chat/chat.service.ts
  nestjs/src/chat/chatParticipant.repository.ts
  nestjs/src/chat/dto/chatParticipantAuthority.dto.ts
Labels: 💫feat

#132 게임 종료 및 종료 이후 이벤트 및 자원 관리
  nestjs/src/filter/unauthorized-exception.filter.ts
  nestjs/src/socket/game/class/game.ts
  nestjs/src/socket/game/class/gamePlayer.ts
  nestjs/src/socket/game/class/matchHistory.ts
  nestjs/src/socket/game/class/user.ts
  nestjs/src/socket/game/dto/createGameHistory.dto.ts
  nestjs/src/socket/game/entities/gameHistory.entity.ts
  nestjs/src/socket/game/enum/gameStatus.enum.ts
  nestjs/src/socket/game/enum/gameType.enum.ts
  nestjs/src/socket/game/gameHistory.repository.ts
  nestjs/src/socket/game/gameSocket.gateway.ts
  nestjs/src/socket/game/gameSocket.module.ts
  nestjs/src/socket/game/gameSocket.service.ts
Labels: 🐛bug, 💫feat, ⚙️chore

#138 게임의 전반 적인 라이프사이클 도중 유저가 offline이 되었을 때 로직 처리
  nestjs/src/socket/game/gameSocket.gateway.ts
  nestjs/src/socket/game/gameSocket.service.ts
Labels: 💫feat

#149 게임 중 상대방 소켓이 끊겼을 때 이벤트 전송 순서에 따른 버그
  nestjs/src/socket/game/enum/gameStatus.enum.ts
  nestjs/src/socket/game/gameSocket.gateway.ts
  nestjs/src/socket/game/gameSocket.service.ts
Labels: 🐛bug

#140 Feat ban과 kick에 대한 소켓 이벤트 생성
  nestjs/src/socket/home/connection.service.ts
  nestjs/src/socket/home/dto/mute.dto.ts
  nestjs/src/socket/home/dto/skill.dto.ts
  nestjs/src/socket/home/home.gateway.ts
  nestjs/src/socket/home/message.service.ts
Labels: ♻️refactor, 💫feat

#143 게임 접속 상태를 관리하는 별도의 서비스 만들기
  nestjs/src/socket/game/gameConnection.service.ts
  nestjs/src/socket/game/gameSocket.gateway.ts
  nestjs/src/socket/game/gameSocket.module.ts
Labels: 💫feat

#142 [Feat]: private 채팅방 구현
  nestjs/src/chat/chat.controller.ts
  nestjs/src/chat/chat.respository.ts
  nestjs/src/chat/chat.service.ts
  nestjs/src/chat/chatParticipant.repository.ts
Labels: 💫feat

#156 Feat 151 achievement profile 검색
  nestjs/src/achievement/dto/getAchievement.dto.ts
  nestjs/src/profile/dto/searchUser.dto.ts
  nestjs/src/profile/profile.module.ts
  nestjs/src/profile/profile.service.ts
Labels: 💫feat

#154 [fix] friend request save시에 await 처리
  nestjs/src/friend/friendRequesting.repository.ts
Labels: 🐛bug

#153 Hotfix 함수명변경
  nestjs/src/chat/chat.controller.ts
  nestjs/src/chat/chat.respository.ts
  nestjs/src/chat/chatParticipant.repository.ts
  nestjs/src/socket/home/blackList.repository.ts
  nestjs/src/socket/home/dto/userId.dto.ts
  nestjs/src/socket/home/entities/blackList.entity.ts
  nestjs/src/socket/home/home.gateway.ts
  nestjs/src/socket/home/home.module.ts
  nestjs/src/socket/home/message.service.ts
Labels: ♻️refactor

#155 Feat 129 achivement 기능 생성 && hotfix Merge
  nestjs/src/achievement/achievement.module.ts
  nestjs/src/achievement/achievement.repository.ts
  nestjs/src/achievement/achievementSeeder.service.ts
  nestjs/src/achievement/dto/getAchievement.dto.ts
  nestjs/src/achievement/entities/Achievement.entity.ts
  nestjs/src/achievement/entities/UserAchievement.entity.ts
  nestjs/src/achievement/strategy/friendsCount.strategy.ts
  nestjs/src/achievement/strategy/interface/achievementStrategy.interface.ts
  nestjs/src/achievement/subscriber/friend.subscriber.ts
  nestjs/src/achievement/userAchievement.repository.ts
  nestjs/src/app.module.ts
  nestjs/src/filter/unauthorized-exception.filter.ts
  nestjs/src/main.ts
  nestjs/src/profile/dto/searchUser.dto.ts
  nestjs/src/profile/profile.module.ts
  nestjs/src/profile/profile.service.ts
Labels: 💫feat

#159 Feat 157 aes 256 otp key에 적용
  nestjs/src/auth/auth.module.ts
  nestjs/src/auth/auth.service.ts
  nestjs/src/auth/utils/crypto.service.ts
  nestjs/src/profile/dto/otpSetup.dto.ts
  nestjs/src/profile/profile.module.ts
  nestjs/src/profile/profile.service.ts
Labels: 💫feat

#162 game url 직접 접근 막는 로직 작성
  nestjs/src/socket/game/enum/userStatus.enum.ts
  nestjs/src/socket/game/gameSocket.gateway.ts
  nestjs/src/socket/game/gameSocket.service.ts
Labels: 🐛bug, 💫feat, ⚙️chore

#164 게임 히스토리 저장 버그
  nestjs/src/socket/game/gameSocket.gateway.ts
  nestjs/src/socket/game/gameSocket.service.ts
Labels: 🐛bug

#166 Hotfix mute kick 오류수정
  nestjs/src/chat/chat.service.ts
  nestjs/src/chat/chatParticipant.repository.ts
  nestjs/src/socket/home/connection.service.ts
  nestjs/src/socket/home/dto/directMessage.dto.ts
  nestjs/src/socket/home/dto/message.dto.ts
  nestjs/src/socket/home/dto/roomId.dto.ts
  nestjs/src/socket/home/dto/skill.dto.ts
  nestjs/src/socket/home/dto/userId.dto.ts
  nestjs/src/socket/home/home.gateway.ts
  nestjs/src/socket/home/message.service.ts
Labels: 🐛bug, ♻️refactor

#170 [Fix]: boss가 ban이 되는 현상 Fix
  nestjs/src/chat/chat.service.ts
Labels: 🐛bug, ♻️refactor

#174 래더점수 엔티티 생성 및 래더 점수 계산 로직 구현
  nestjs/src/socket/game/class/matchHistory.ts
  nestjs/src/socket/game/dto/createLadder.dto.ts
  nestjs/src/socket/game/entities/ladder.entity.ts
  nestjs/src/socket/game/enum/gameStatus.enum.ts
  nestjs/src/socket/game/gameHistory.repository.ts
  nestjs/src/socket/game/gameSocket.gateway.ts
  nestjs/src/socket/game/gameSocket.module.ts
  nestjs/src/socket/game/gameSocket.service.ts
  nestjs/src/socket/game/ladder.repository.ts
Labels: 💫feat

#188 generalgameservice 구현
  nestjs/src/socket/home/generalGame.service.ts
  nestjs/src/socket/home/home.module.ts
Labels: 💫feat

#196 GeneralGameApprove 이벤트 핸들러 구현
  nestjs/src/socket/game/gameConnection.service.ts
  nestjs/src/socket/game/gameSocket.gateway.ts
  nestjs/src/socket/game/gameSocket.module.ts
Labels: 💫feat

#198 general game 검증 로직 및 예외처리 구현
  nestjs/src/socket/game/gameSocket.gateway.ts
  nestjs/src/socket/home/generalGame.service.ts
Labels: 💫feat

#202 게임소켓에서 오류가 나는 문제
  nestjs/src/socket/game/gameSocket.gateway.ts
Labels: 🐛bug, ♻️refactor

#221 [Hotfix]: 채팅 참여하고 있는 모든 참여자에게 소켓 이벤트를 보내주도록 수정
  nestjs/src/socket/home/home.gateway.ts
Labels: ♻️refactor

#222 Hotfix chat 주석삭제
  nestjs/src/socket/home/home.gateway.ts
Labels: ♻️refactor

#220 게임 플레이 관련 옵션 값 수정
  nestjs/src/socket/game/enum/initStatus.enum.ts
  nestjs/src/socket/game/gameSocket.service.ts
Labels: 💫feat

#228 game 관련 서비스 strict 모드로 컴파일하고 수정
  nestjs/src/socket/game/class/game.ts
  nestjs/src/socket/game/gameConnection.service.ts
  nestjs/src/socket/game/gameSocket.gateway.ts
  nestjs/src/socket/game/gameSocket.service.ts
Labels: ♻️refactor
